<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: organization.proto

namespace Goforphp\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *操作返回结构体，0表示成功，其他数值为失败
 *
 * Generated from protobuf message <code>proto.DoResponse</code>
 */
class DoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 message = 1;</code>
     */
    private $message = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $message
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Organization::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 message = 1;</code>
     * @return int
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>int32 message = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkInt32($var);
        $this->message = $var;

        return $this;
    }

}

